[package]
name = "rusty-chunkenc"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22"
nom = "7.1"
once_cell = "1.19"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
crc32c = "0.6"
xxhash-rust = { version = "0.8", features = ["xxh64"] }
